FROM    nginx
COPY    ./default.conf /etc/nginx/conf.d/default.conf
# RUN     mkdir -p /usr/share/nginx/html/app
# RUN     mkdir -p /usr/share/nginx/app-1/build
RUN     mkdir -p /usr/share/nginx/app-2/build